version: '3'

volumes:
  adapt-db:
  adapt-configdb:
  adapt-data:

services:
  db:
    container_name: adapt-db
    image: mongo
    volumes:
      - adapt-db:/data/db
      - adapt-configdb:/data/configdb
  authoring:
    container_name: adapt-authoring
    image: darioseidl/adapt-authoring:0.5.0
    volumes:
      - adapt-data:/adapt_authoring
    links:
      - db
    ports:
      - "5000:80"
