version: '3'

volumes:
  adapt-db:
  adapt-configdb:
  adapt-data:
  vsftpd-data:
  vsftpd-logs:
  portainer_data:

services:
  mongo:
    container_name: adapt-db
    image: mongo
    restart: always
    volumes:
      - adapt-db:/data/db
      - adapt-configdb:/data/configdb
  adapt-authoring:
    container_name: adapt-authoring
    image: rechnerherz/adapt-authoring:0.11.3
    restart: always
    volumes:
      - adapt-data:/adapt_authoring
  vsftpd:
    container_name: vsftpd
    image: fauria/vsftpd
    restart: always
    volumes:
      - vsftpd-data:/home/vsftpd
      - vsftpd-logs:/var/log/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100-21109:21100-21109"
    environment:
      FTP_USER: aatftp
      FTP_PASS: "$ADAPT_FTP_PASSWORD"
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: "21100"
      PASV_MAX_PORT: "21109"
  adminmongo:
    container_name: adminmongo
    image: mrvautin/adminmongo
    restart: always
    environment:
      PASSWORD: "$ADAPT_ADMINMONGO_PASSWORD"
      CONTEXT: "adminmongo"
    command: /bin/sh -c "rm config/app.json; node app.js"
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  nginx:
    container_name: adapt-nginx
    image: nginx:1.19.5
    restart: always
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ../nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ../nginx-certbot/data/certbot/www:/var/www/certbot
    depends_on:
      - adapt-authoring
      - adminmongo
      - portainer
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../nginx-certbot/data/certbot/conf:/etc/letsencrypt
      - ../nginx-certbot/data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
