version: '3'

volumes:
  adapt-db2:
  adapt-configdb2:
  adapt-data2:
  vsftpd-data:
  vsftpd-logs:
  portainer_data:

services:
  mongo:
    container_name: adapt-db2
    image: mongo
    restart: always
    volumes:
      - adapt-db2:/data/db
      - adapt-configdb2:/data/configdb
  adapt-authoring:
    container_name: adapt-authoring2
    image: darioseidl/adapt-authoring:0.10.5
    restart: always
    volumes:
      - adapt-data2:/adapt_authoring
  vsftpd:
    container_name: vsftpd
    image: fauria/vsftpd
    restart: always
    volumes:
      - vsftpd-data:/home/vsftpd
      - vsftpd-logs:/var/log/vsftpd
    ports:
      - 20:20
      - 21:21
      - 21100-21109:21100-21109
    environment:
      FTP_USER: aatftp
      FTP_PASS: "$ADAPT_FTP_PASSWORD"
      PASV_ADDRESS: 127.0.0.1
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21109
  adminmongo:
    container_name: adminmongo
    image: mrvautin/adminmongo
    restart: always
    environment:
      PASSWORD: "$ADAPT_ADMINMONGO_PASSWORD"
    command: /bin/sh -c "rm config/app.json; node app.js"
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  nginx:
    container_name: adapt-nginx
    image: nginx:1.19.5
    restart: always
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./out/fullchain.cer:/etc/ssl/adapt/fullchain.pem
      - ./out/learn.macschneider.at.key:/etc/ssl/adapt/privkey.pem
    environment:
      NGINX_SERVER_NAME: "$ADAPT_NGINX_SERVER_NAME"
    depends_on:
      - adapt-authoring
      - adminmongo
      - portainer
